### ISSUE TITLE
auth() doesn't set the actual password parameter

### ISSUE THREAD

**Issue by tobilg** [phulst/node-tile38#11]
It seems like the `auth()` command doesn't set the supplied password, see https://github.com/phulst/node-tile38/blob/master/src/tile38.js#L142-L144

I keep seeing errors like 

```javascript
events.js:165
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: ERR authentication required
    at parseError (/var/www/backend/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/var/www/backend/node_modules/redis-parser/lib/parser.js:303:14)
Emitted 'error' event at:
    at RedisClient.on_info_cmd (/var/www/backend/node_modules/redis/index.js:496:14)
    at /var/www/backend/node_modules/redis/index.js:535:14
    at Object.callbackOrEmit [as callback_or_emit] (/var/www/backend/node_modules/redis/lib/utils.js:89:9)
    at /var/www/backend/node_modules/redis/lib/individualCommands.js:157:15
    at Object.callbackOrEmit [as callback_or_emit] (/var/www/backend/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/var/www/backend/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/var/www/backend/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/var/www/backend/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/var/www/backend/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:581:20)
```

**Comment by phulst** [comment]
thanks for reporting. This is now fixed in 0.6.5
