### ISSUE TITLE
test case failing for 'bounds'

### ISSUE THREAD

**Issue by KrishnaPG** [phulst/node-tile38#18]
Downloaded, and ran the test cases. It is passing all, except for one, as shown below. This is against the latest tile38 server running.
````
  key commands
    bounds
Unhandled rejection TypeError: Cannot read property 'lat' of undefined
    at tile38.bounds.then (C:\Users\user\Desktop\node-tile38\test\test_keys_commands.js:24:27)
    at tryCatcher (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user\Desktop\node-tile38\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

      1) should return bounds for a key
````

**Comment by phulst** [comment]
Thanks for reporting. It looks like the Tile38 response on the bounds command has changed. Before it would return an object with 'sw' and 'ne' properties (containing GPS coordinates). The latest versions of Tile38 are now returning a Geojson polygon instead. I'll update the test cases, but other than that won't need to make any changes.
