### ISSUE TITLE
executeGeoFence error

### ISSUE THREAD

**Issue by behrad** [phulst/node-tile38#7]
I'm getting 
```
sending live fence command "NEARBY adp-nms-push FENCE POINT 33.1212 -122.2423 1000"
TypeError: "string" must be a string, Buffer, or ArrayBuffer
```
in this code
```js
const query = geoClient.nearbyQuery('adp-nms-push')
                .detect('enter', 'exit')
                .point(33.1212, -122.2423, 1000)
const fence = query.executeFence()
```

node version: v8.9.1
node-tile38 version: 0.6.4

**Comment by behrad** [comment]
I changed numbers to string, command seems successful but now tile38 server is crashing after executeFence:

node-client console:
```
sending live fence command "NEARBY adp-nms-push FENCE DETECT enter,exit POINT 33.12 -122.23 100"
GeoFence was closed 
Mon, 15 Jan 2018 08:17:43 GMT uncaughtException: Redis connection to 10.10.101.148:9851 failed - connect ECONNREFUSED 10.10.101.148:9851
Error: Redis connection to 10.10.101.148:9851 failed - connect ECONNREFUSED 10.10.101.148:9851
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```
@phulst

And tile38 server error:

```
Jan 15 11:44:38 test-broker3 tile38-server: panic: runtime error: index out of range
Jan 15 11:44:38 test-broker3 tile38-server: goroutine 73 [running]:
Jan 15 11:44:38 test-broker3 tile38-server: github.com/tidwall/tile38/controller/server.(*PipelineReader).ReadMessages(0xc420782000, 0xc4201142a0, 0x1100000000006, 0x20b00010028, 0x0, 0xc420782000)
Jan 15 11:44:38 test-broker3 tile38-server: /var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/reader.go:227 +0xb3c
Jan 15 11:44:38 test-broker3 tile38-server: github.com/tidwall/tile38/controller/server.handleConn.func2(0xc420782000, 0x10f9601, 0xc420039f60, 0xc42018a850, 0xc420364c40, 0xc420142920, 0x0)
Jan 15 11:44:38 test-broker3 tile38-server: /var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/server.go:118 +0x40
Jan 15 11:44:38 test-broker3 tile38-server: github.com/tidwall/tile38/controller/server.handleConn(0xc420142920, 0xc42037c020, 0xc420364c40, 0xc42037c040, 0xc420364c50, 0x1)
Jan 15 11:44:38 test-broker3 tile38-server: /var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/server.go:161 +0x244
Jan 15 11:44:38 test-broker3 tile38-server: created by github.com/tidwall/tile38/controller/server.ListenAndServe
Jan 15 11:44:38 test-broker3 tile38-server: /var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/server.go:80 +0x29a
Jan 15 11:44:38 test-broker3 systemd: tile38.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 15 11:44:38 test-broker3 systemd: Unit tile38.service entered failed state.
Jan 15 11:44:38 test-broker3 systemd: tile38.service failed.
```
@tidwall

**Comment by phulst** [comment]
I tested this and it works fine for me. I'm assuming this was caused by the bug that @tidwall fixed a while ago. 
The executeFence() function does require you to pass in a callback method, otherwise it may throw an exception, but without a callback it would be pointless to call executeFence so I'm not inclined to do anything about that.
